name: Update version
on:
  repository_dispatch:
    types:
      - pact-cli-released
      - pact-verifier-cli-released
      - pact-stub-cli-released
      - pact-plugin-cli-released
      - pact-mock-cli-released
      - pact-standalone-released
  workflow_dispatch:
    inputs:
      type:
        description: 'Type of release'
        required: true
        type: choice
        options:
          - pact-cli-released
          - pact-verifier-cli-released
          - pact-stub-cli-released
          - pact-plugin-cli-released
          - pact-mock-cli-released
          - pact-standalone-released
      version:
        description: 'Version to update to'
        required: true
        type: string

jobs:
  release:
    name: Release update
    runs-on: macOS-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Config github actor
        run: |
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git config --global user.name "${GITHUB_ACTOR}"
          git config pull.ff only

      - name: Set script to run based on type of dispatch
        id: set-script
        run: |
          TYPE="${{ github.event.client_payload.type || github.event.inputs.type }}"
          VERSION="${{ github.event.client_payload.version || github.event.inputs.version }}"
          
          case "$TYPE" in
            pact-cli-released)
              echo "SCRIPT=scripts/update_tap_version_pact_cli.sh" >> $GITHUB_ENV
              ;;
            pact-verifier-cli-released)
              echo "SCRIPT=scripts/update_tap_version_verifier_cli.sh" >> $GITHUB_ENV
              ;;
            pact-stub-cli-released)
              echo "SCRIPT=scripts/update_tap_version_stub_cli.sh" >> $GITHUB_ENV
              ;;
            pact-plugin-cli-released)
              echo "SCRIPT=scripts/update_tap_version_plugin_cli.sh" >> $GITHUB_ENV
              ;;
            pact-standalone-released)
              echo "SCRIPT=scripts/update_legacy_tap_version.sh" >> $GITHUB_ENV
              ;;
            *)
              echo "Unknown type: $TYPE"
              exit 1
              ;;
          esac
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Run update script
        run: |
          ./$SCRIPT $VERSION
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
          CREATE_PR: true